name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  setup:
    name: Rails CI Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Precompile assets
        run: bundle exec rails assets:precompile

      # --- OPTIONAL FUTURE TASKS ---

      # - name: Run RuboCop linter
      #   run: bin/rubocop -f github

      # - name: Run security scan (Brakeman)
      #   run: bin/brakeman --no-pager

      # - name: Run importmap audit (JS security check)
      #   run: bin/importmap audit

      # - name: Run test suite
      #   env:
      #     RAILS_ENV: test
      #   run: |
      #     bin/rails db:test:prepare
      #     bin/rails test
      #     bin/rails test:system

      # - name: Upload screenshots on test failure
      #   uses: actions/upload-artifact@v4
      #   if: failure()
      #   with:
      #     name: screenshots
      #     path: ${{ github.workspace }}/tmp/screenshots
      #     if-no-files-found: ignore

      # - name: Install Chrome for system tests
      #   run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2

      # - name: Setup Redis (if needed in future)
      #   services:
      #     redis:
      #       image: redis
      #       ports:
      #         - 6379:6379
      #       options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5